JBApp/catalogue/urls.py
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('tees/', views.cat1, name="tees"),
    path('hoodies_sweater/', views.cat2, name="hoodies_sweater"),
    path('pants/', views.cat3, name="pants"),
    path('exclusive_apparel/', views.cat4, name="exclusive_apparel")
]

JBApp/jollyboys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalogue/', include('catalogue.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JBApp/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about")
]

JBApp/catalogue/models.py
from django.db import models
import os
# Create your models here

def path_and_rename(name, filename):
    upload_to = 'images/'
    ext = filename.split('.')[-1]
    # get filename
    filename = '{}.{}'.format(name, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)

class Tee(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.FloatField(default=0, null=True, blank=True)
    size = models.CharField(max_length=200, null=True)
    length = models.CharField(max_length=200, null=True)
    ptp = models.CharField(max_length=200, null=True)
    sold = models.BooleanField(default=False, null=True)
    image = models.ImageField(upload_to=path_and_rename, height_field=None, width_field=None, max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Pant(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.FloatField(default=0, null=True, blank=True)
    waist = models.CharField(max_length=200, null=True)
    inseam = models.CharField(max_length=200, null=True)
    rise = models.CharField(max_length=200, null=True)
    sold = models.BooleanField(default=False, null=True)
    image = models.ImageField(upload_to=path_and_rename, height_field=None, width_field=None, max_length=100, null=True,
                              blank=True)

    def __str__(self):
        return self.name

class Hoodies_Sweater(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.FloatField(default=0, null=True, blank=True)
    size = models.CharField(max_length=200, null=True)
    length = models.CharField(max_length=200, null=True)
    ptp = models.CharField(max_length=200, null=True)
    sold = models.BooleanField(default=False, null=True)
    image = models.ImageField(upload_to=path_and_rename, height_field=None, width_field=None, max_length=100, null=True,
                              blank=True)

    def __str__(self):
        return self.name

class Exclusive_Apparel(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.FloatField(default=0, null=True, blank=True)
    size = models.CharField(max_length=200, null=True)
    length = models.CharField(max_length=200, null=True)
    ptp = models.CharField(max_length=200, null=True)
    sold = models.BooleanField(default=False, null=True)
    image = models.ImageField(upload_to=path_and_rename, height_field=None, width_field=None, max_length=100, null=True,
                              blank=True)

    def __str__(self):
        return self.name

JBApp/main/models.py
from django.db import models

# Create your models here.

JBApp/catalogue/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Tee, Exclusive_Apparel, Pant, Hoodies_Sweater


# Create your views here.

def cat1(request):
    tees = Tee.objects.all()
    return render(request, 'catalogue/teecatalogue.html', {'tees': tees})


def cat2(request):
    hoodies_sweaters = Hoodies_Sweater.objects.all()
    return render(request, 'catalogue/hoodiescatalogue.html', {'hoodies_sweaters': hoodies_sweaters})


def cat3(request):
    pants = Pant.objects.all()
    return render(request, 'catalogue/pantscatalogue.html', {'pants': pants})


def cat4(request):
    exclusive_apparel = Exclusive_Apparel.objects.all()
    return render(request, 'catalogue/exclusivecatalogue.html', {'exclusive_apparel': exclusive_apparel})

JBApp/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    # return HttpResponse('Jollyboys Main Page')
    return render(request, 'main/index.html')

def about(request):
    return render(request, 'main/about.html')

JBApp/catalogue/templates/catalogue/exclusivecatalogue.html
{% load static %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Catalogue</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Directory -->
    <div class="directory">
        <table class="directory-header">
            <tr>
                <th><a href="{% url 'main:index' %}"><img class="small-icon" src="{% static 'main/images/jollyboysicon.jpg' %}"></a></th>
                <th><a class="link-bar" href="{% url 'main:about' %}">About</a></th>
                <th><img class="brand-title" src="{% static 'main/images/jollyboys-brand-title.png' %}"></th>
                <th><a style="position:absolute; right:15px; top:0px;" href="#"><img class="small-icon" src="{% static 'main/images/shopping-bag-icon.jpeg' %}"></a></th>
            </tr>
        </table>
    </div>
<!--     For future, I could add a searchbar which will query by clothes.name-->
    <div style="padding-top:5px;" class="container-fluid">
        <div style="padding-top: 30px;" class="row">
            {% for listing in pants %}
            <div class="ps-5 pb-5 col-md-auto">
            <div class="ps-5 pb-5 col-md-auto">
            <div class="ps-5 pb-5 col-md-auto">
<!--                    Ill will need to style inside this th to make it look like a frame-->
<!--                    perhaps add if condition and change the aesthetic of listing if its sold-->
                <img style="max-height:250px; max-width:250px; display:inline-block;" class="listing-img" src="{{listing.image.url}}">
                <p class="pe-3 pt-2 listing-title">{{listing.name}}</p>
                <h5 class="pe-1 listing-desc">{{listing.size}}</h5>
<!--                <p class="pe-3 listing-desc">{{listing.length}}</p>-->
<!--                <p class="pe-5 listing-desc">{{listing.ptp}}</p>-->
                <h5 class="ps-2 listing-price">${{listing.price}}</h5>
<!--                api call here to add item to cart-->
                <a class="cart-button" href="#">
                    <button type="button" class="btn btn-success">Add to Cart</button>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
<!--Social media tag-->
    <div class="pt-3 container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">
                    <img class="small-icon" src="{% static 'main/images/instagram-icon.png' %}">
                </a>
            </div>
            <div class="pt-2 col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">Instagram</a>
            </div>
        </div>
        <div class="pt-3 pb-3 row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">
                    <img class="small-icon" src="{% static 'main/images/tiktok-icon.png' %}">
                </a>
            </div>
            <div class="pt-3 pe-5 col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">Tiktok</a>
            </div>
        </div>
    </div>
</body>
</html>

JBApp/catalogue/templates/catalogue/hoodiescatalogue.html
{% load static %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Catalogue</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300&display=swap" rel="stylesheet">
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
</head>
<body>
    <!-- Directory -->
     <div class="directory">
        <table class="directory-header">
            <tr>
                <th><a href="{% url 'main:index' %}"><img class="small-icon" src="{% static 'main/images/jollyboysicon.jpg' %}"></a></th>
                <th><a class="link-bar" href="{% url 'main:about' %}">About</a></th>
                <th><img class="brand-title" src="{% static 'main/images/jollyboys-brand-title.png' %}"></th>
                <th><a style="position:absolute; right:15px; top:0px;" href="#"><img class="small-icon" src="{% static 'main/images/shopping-bag-icon.jpeg' %}"></a></th>
            </tr>
        </table>
    </div>
<!--     For future, I could add a searchbar which will query by clothes.name-->
<!--     Listing-->
   <div style="padding-top:5px;" class="container-fluid">
        <div style="padding-top: 30px;" class="row">
            {% for listing in hoodies_sweaters %}
            <div class="ps-5 pb-5 col-md-auto">
<!--                    Ill will need to style inside this th to make it look like a frame-->
<!--                    perhaps add if condition and change the aesthetic of listing if its sold-->
                <img style="max-height:250px; max-width:250px; display:inline-block;" class="listing-img" src="{{listing.image.url}}">
                <p class="pe-3 pt-2 listing-title">{{listing.name}}</p>
                <h5 class="pe-1 listing-desc">{{listing.size}}</h5>
<!--                <p class="pe-3 listing-desc">{{listing.length}}</p>-->
<!--                <p class="pe-5 listing-desc">{{listing.ptp}}</p>-->
                <h5 class="ps-2 listing-price">${{listing.price}}</h5>
<!--                api call here to add item to cart-->
                <a class="cart-button" href="#">
                    <button type="button" class="btn btn-success">Add to Cart</button>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
<!--Social media tag-->
    <div class="pt-3 container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">
                    <img class="small-icon" src="{% static 'main/images/instagram-icon.png' %}">
                </a>
            </div>
            <div class="pt-2 col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">Instagram</a>
            </div>
        </div>
        <div class="pt-3 pb-3 row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">
                    <img class="small-icon" src="{% static 'main/images/tiktok-icon.png' %}">
                </a>
            </div>
            <div class="pt-3 pe-5 col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">Tiktok</a>
            </div>
        </div>
    </div>
</body>
</html>

JBApp/catalogue/templates/catalogue/pantscatalogue.html
{% load static %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Catalogue</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300&display=swap" rel="stylesheet">
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
</head>
<body>
    <!-- Directory -->
    <div class="directory">
        <table class="directory-header">
            <tr>
                <th><a href="{% url 'main:index' %}"><img class="small-icon" src="{% static 'main/images/jollyboysicon.jpg' %}"></a></th>
                <th><a class="link-bar" href="{% url 'main:about' %}">About</a></th>
                <th><img class="brand-title" src="{% static 'main/images/jollyboys-brand-title.png' %}"></th>
                <th><a style="position:absolute; right:15px; top:0px;" href="#"><img class="small-icon" src="{% static 'main/images/shopping-bag-icon.jpeg' %}"></a></th>
            </tr>
        </table>
    </div>
<!--     For future, I could add a searchbar which will query by clothes.name-->
    <div style="padding-top:5px;" class="container-fluid">
        <div style="padding-top: 30px;" class="row">
            {% for listing in pants %}
            <div class="ps-5 pb-5 col-md-auto">
<!--                    Ill will need to style inside this th to make it look like a frame-->
<!--                    perhaps add if condition and change the aesthetic of listing if its sold-->
                <img style="max-height:250px; max-width:250px; display:inline-block;" class="listing-img" src="{{listing.image.url}}">
                <p class="pe-3 pt-2 listing-title">{{listing.name}}</p>
                <h5 class="pe-1 listing-desc">{{listing.size}}</h5>
<!--                <p class="pe-3 listing-desc">{{listing.length}}</p>-->
<!--                <p class="pe-5 listing-desc">{{listing.ptp}}</p>-->
                <h5 class="ps-2 listing-price">${{listing.price}}</h5>
<!--                api call here to add item to cart-->
                <a class="cart-button" href="#">
                    <button type="button" class="btn btn-success">Add to Cart</button>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
<!--Social media tag-->
    <div class="pt-3 container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">
                    <img class="small-icon" src="{% static 'main/images/instagram-icon.png' %}">
                </a>
            </div>
            <div class="pt-2 col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">Instagram</a>
            </div>
        </div>
        <div class="pt-3 pb-3 row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">
                    <img class="small-icon" src="{% static 'main/images/tiktok-icon.png' %}">
                </a>
            </div>
            <div class="pt-3 pe-5 col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">Tiktok</a>
            </div>
        </div>
    </div>
</body>
</html>

JBApp/catalogue/templates/catalogue/teecatalogue.html
{% load static %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Catalogue</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300&display=swap" rel="stylesheet">
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
</head>
<body>
    <!-- Directory -->
    <div class="directory">
        <table class="directory-header">
           <tr>
                <th><a href="{% url 'main:index' %}"><img class="small-icon" src="{% static 'main/images/jollyboysicon.jpg' %}"></a></th>
                <th><a class="link-bar" href="{% url 'main:about' %}">About</a></th>
                <th><img class="brand-title" src="{% static 'main/images/jollyboys-brand-title.png' %}"></th>
                <th><a style="position:absolute; right:15px; top:0px;" href="#"><img class="small-icon" src="{% static 'main/images/shopping-bag-icon.jpeg' %}"></a></th>
            </tr>
        </table>
    </div>
<!--     For future, I could add a searchbar which will query by clothes.name-->
    <div style="padding-top:5px;" class="container-fluid">
        <div style="padding-top: 30px;" class="row">
            {% for listing in tees %}
            <div class="ps-5 pb-5 col-md-auto">
<!--                    Ill will need to style inside this th to make it look like a frame-->
<!--                    perhaps add if condition and change the aesthetic of listing if its sold-->
                <img style="max-height:280px; max-width:280px; display:inline-block;" class="listing-img" src="{{listing.image.url}}">
                <p class="pe-3 pt-2 listing-title">{{listing.name}}</p>
                <h5 class="mb-2 badge rounded-pill bg-secondary listing-desc">{{listing.size}}</h5>
<!--                <p class="pe-3 listing-desc">{{listing.length}}</p>-->
<!--                <p class="pe-5 listing-desc">{{listing.ptp}}</p>-->
                <h5 class="ps-2 listing-price">${{listing.price}}</h5>
<!--                api call here to add item to cart-->
                <a class="cart-button" href="#">
                    <button type="button" class="btn btn-success">Add to Cart</button>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <!--Social media tag-->
    <div class="pt-3 container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">
                    <img class="small-icon" src="{% static 'main/images/instagram-icon.png' %}">
                </a>
            </div>
            <div class="pt-2 col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">Instagram</a>
            </div>
        </div>
        <div class="pt-3 pb-3 row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">
                    <img class="small-icon" src="{% static 'main/images/tiktok-icon.png' %}">
                </a>
            </div>
            <div class="pt-3 pe-5 col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">Tiktok</a>
            </div>
        </div>
    </div>
</body>
</html>

JBApp/main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>JollyBoys Main Page</title>
    <link rel="icon" href="{% static 'main/images/jollyboy-favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500&family=Sora:wght@300&display=swap" rel="stylesheet">
</head>

<body>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>-->

    <!--Directory-->
    <div class="directory">
        <table class="directory-header">
            <tr>
                <th><a href="{% url 'main:index' %}"><img class="small-icon" src="{% static 'main/images/jollyboysicon.jpg' %}"></a></th>
                <th><a class="link-bar" href="{% url 'main:index' %}">Home</a></th>
                <th><a class="link-bar" href="{% url 'main:about' %}">About</a></th>
                <th><img class="brand-title" src="{% static 'main/images/jollyboys-brand-title.png' %}"></th>
                <th><a style="position:absolute; right:15px; top:0px;" href="#"><img class="small-icon" src="{% static 'main/images/shopping-bag-icon.jpeg' %}"></a></th>
            </tr>
        </table>
    </div>

    <!-- Main Content -->
    <div style="padding-top:5px;" class="container-fluid">
        <div class="row">
            <div style="padding:0px;" class="col" >
                <a class="categories" href="{% url 'catalogue:tees' %}">
                    <img class="cat-image" style="max-width:100%; max-height:100%;" src="{% static 'main/images/covertee.jpg' %}" alt="covertee">
                    <h2 class="cat-header">Tees</h2>
                    <h2 class="cat-popup">Click to see Tees Catalogue</h2>
                </a>
            </div>
            <div style="padding:0px;" class="col">
                <a class="categories" href="{% url 'catalogue:hoodies_sweater' %}">
                    <img class="cat-image" style="max-width:100%; max-height:100%;" src="{% static 'main/images/coverhoodie.jpg' %}" alt="coverhoodie">
                    <h2 class="cat-header">Hoodies/Sweaters</h2>
                    <h2 class="cat-popup">Click to see Hoodies/Sweaters Catalogue</h2>
                </a>
            </div>
        </div>
        <div class="row">
            <div style="padding:0px;" class="col">
                <a class="categories" href="{% url 'catalogue:pants' %}">
                    <img class="cat-image" style="max-width:100%; max-height:100%;" src="{% static 'main/images/coverpants.jpg' %}" alt="coverpants">
                    <h2 class="cat-header">Pants</h2>
                    <h2 class="cat-popup">Click to see Pants Catalogue</h2>
                </a>
            </div>
            <div style="padding:0px;" class="col">
                <a class="categories" href="{% url 'catalogue:exclusive_apparel' %}">
                    <img class="cat-image" style="max-width:100%; max-height:100%;" src="{% static 'main/images/coverexclusive.jpg' %}" alt="coverexclusive">
                    <h2 class="cat-header">Exclusive Apparel</h2>
                    <h2 class="cat-popup">Click to see Exclusive Apparel Catalogue</h2>
                </a>
            </div>
        </div>
    </div>
    <!--Social media tag-->
    <div class="pt-3 container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">
                    <img class="small-icon" src="{% static 'main/images/instagram-icon.png' %}">
                </a>
            </div>
            <div class="pt-2 col-md-auto">
                <a class="media-bar" target="_blank" href="https://instagram.com/jollyboys.vtg?utm_medium=copy_link">Instagram</a>
            </div>
        </div>
        <div class="pt-3 pb-3 row justify-content-md-center">
            <div class="col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">
                    <img class="small-icon" src="{% static 'main/images/tiktok-icon.png' %}">
                </a>
            </div>
            <div class="pt-3 pe-5 col-md-auto">
                <a class="media-bar" target="_blank" href="https://www.tiktok.com/@jollyboysvtg?_t=8UbxfX7UTtS">Tiktok</a>
            </div>
        </div>
    </div>
</body>
</html>